[workspace]
members = ["crates/xal-host", "crates/xal-native", "crates/xal-plugin-diagnostics", "crates/xal-plugin-inspect", "crates/xal-rust", "crates/xal-plugin-workspace", "crates/xal-plugin-openai", "crates/xal-services"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[profile.release]
panic = "unwind"
