[package]
name = "xal-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version = "1.92"

[lib]
crate-type = ["cdylib"]

[dependencies]
globset = "=0.4.20"
grep-matcher = "=0.1.8"
grep-regex = "=0.1.14"
grep-searcher = "=0.1.16"
ignore = "=0.4.25"
napi = { version = "=3.12.1", default-features = false, features = ["dyn-symbols", "napi4"] }
napi-derive = "=3.6.3"

[build-dependencies]
napi-build = "=2.4.1"
